[package]
name = "simpler-logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "logger-tests"
path = "source/main.rs"

[dependencies]
log = "0.4.20"